# ETAPA 1
FROM node:22.13.1 AS  build

WORKDIR /app

COPY package.json /app

RUN npm install 

COPY . .

RUN npm run build --configuration=production

# ETAPA 2

FROM nginx:stable-alpine

COPY --from=build  /app/dist/project-home/browser /usr/share/nginx/html

COPY ./nginx-custom.conf  /etc/nginx/conf.d/default.conf