# Etapa 1: Construcción
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app


COPY ["api_minimal.csproj", "./"]
RUN dotnet restore


COPY . .
RUN dotnet publish -c Release -o /out

# Etapa 2: Ejecución
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app


COPY --from=build /out .


EXPOSE 8080

# Comando de inicio
CMD ["dotnet", "api_minimal.dll"]
